[theme]
base = "dark"
primaryColor = "#BE123C"
backgroundColor = "#0B0F14"
secondaryBackgroundColor = "#1E293B"
textColor = "#F8FAFC"
font = "sans-serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true

maxUploadSize = 10

[client]
showErrorDetails = "none"
toolbarMode = "minimal"
